- id: '1573883685626'
  alias: Notify when printer finishes
  description: ''
  trigger:
  - entity_id: sensor.octoprint_current_state
    from: Printing
    platform: state
    to: Operational
  condition: []
  action:
  - data:
      message: Printer has finished
    service: notify.notify_pushbullet
- id: '1575103717785'
  alias: Notify when washing machine finishes
  description: ''
  trigger:
  - below: 5
    device_id: 8ade2b7fee914993b9c0c0603da67237
    domain: sensor
    entity_id: sensor.0x00158d00026e9fa1_power
    for:
      hours: 0
      minutes: 0
      seconds: 10
    platform: device
    type: value
  condition: []
  action:
  - data:
      message: Washing machine has finished
    service: notify.notify_pushbullet
- id: '1576921942730'
  alias: Kodi play/pause
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/ikea_symfonisk_remote_74d44a
  condition:
  - condition: template
    value_template: '{{ ''play_pause'' in trigger.payload }}'
  action:
  - data:
      entity_id: media_player.kodi
    service: media_player.media_play_pause
- id: d09e759079d6459fa6dd5fae89008ea8
  alias: Kodi set volume
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/ikea_symfonisk_remote_74d44a
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == ''rotate_stop'' }}'
  action:
  - data_template:
      entity_id: media_player.kodi
      volume_level: '{{ (trigger.payload_json.brightness / 255) | round(2) }}'
    service: media_player.volume_set
- id: '1578143953944'
  alias: Lounge night light on
  description: ''
  trigger:
  - device_id: cc3f89b81eaf4deaa9499f67a20a8ff9
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d0003f13014_occupancy
    platform: device
    type: motion
  condition:
  - after: '23:00'
    before: 07:00
    condition: time
  - condition: state
    entity_id: light.0xb0ce1814033b6616_light
    state: 'off'
  - condition: template
    value_template: '{{ states(''media_player.kodi'') != ''playing'' }}'
  action:
  - data:
      brightness: 80
      entity_id: light.0xb0ce1814033b6616_light
      transition: 5
    service: light.turn_on
- id: '1578144170489'
  alias: Lounge night light off
  description: ''
  trigger:
  - device_id: cc3f89b81eaf4deaa9499f67a20a8ff9
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d0003f13014_occupancy
    platform: device
    type: no_motion
  condition:
  - after: '23:00'
    before: 07:00
    condition: time
  - condition: template
    value_template: '{{ states(''media_player.kodi'') != ''playing'' }}'
  action:
  - data:
      entity_id: light.0xb0ce1814033b6616_light
    service: light.turn_off
- id: '1578741489934'
  alias: Lamp turned on
  description: ''
  trigger:
  - device_id: 39a1d0389ed145c3a24fafac4c19f00c
    domain: light
    entity_id: light.0xb0ce1814033b6616_light
    platform: device
    type: turned_on
  condition: []
  action:
  - alias: ''
    data:
      payload: 1
      topic: /remote_switch/in
    service: mqtt.publish
- id: '1578741569578'
  alias: Lamp turned off
  description: ''
  trigger:
  - device_id: 39a1d0389ed145c3a24fafac4c19f00c
    domain: light
    entity_id: light.0xb0ce1814033b6616_light
    platform: device
    type: turned_off
  condition: []
  action:
  - data:
      payload: 0
      topic: /remote_switch/in
    service: mqtt.publish
- id: '1578741643740'
  alias: Toggle light on/off
  description: ''
  trigger:
  - platform: mqtt
    topic: /remote_switch/out
  condition: []
  action:
  - device_id: 39a1d0389ed145c3a24fafac4c19f00c
    domain: light
    entity_id: light.0xb0ce1814033b6616_light
    type: toggle
- id: '1579442196325'
  alias: St. George balance changed
  description: ''
  trigger:
  - entity_id: sensor.st_george_balance
    platform: state
  condition: []
  action:
  - data:
      message: St. George balance is ${{ states("sensor.st_george_balance") }}
    service: notify.notify_pushbullet
- id: '1579442256298'
  alias: ING balance changed
  description: ''
  trigger:
  - entity_id: sensor.ing_balance
    platform: state
  condition: []
  action:
  - data:
      message: ING balance is ${{ states("sensor.ing_balance") }}
    service: notify.notify_pushbullet
- id: '1579963381415'
  alias: Toggle north bedroom lamp
  description: ''
  trigger:
  - entity_id: sensor.0x00158d00033e8df9_click
    platform: state
    to: single
  condition: []
  action:
  - device_id: c401a39f2848404b903f1c8776508752
    domain: light
    entity_id: light.0xb0ce1814033b6827_light
    type: toggle
- id: '1579963933873'
  alias: Set north bathroom lamp brightness
  description: ''
  trigger:
  - entity_id: sensor.0x00158d00033e8df9_click
    platform: state
    to: double
  condition: []
  action:
  - alias: ''
    service: light.turn_on
    data_template:
      entity_id: light.0xb0ce1814033b6827_light
      transition: '1'
      brightness: '{{ 255 if state_attr("light.0xb0ce1814033b6827_light", "brightness")
        == 5 else 5 }}'
