- id: '1573380114196'
  alias: Kodi Play/Pause button
  description: ''
  trigger:
  - entity_id: sensor.0x00158d00035a7b66_click
    platform: state
    to: single
  condition: []
  action:
  - data:
      entity_id: media_player.kodi
    service: media_player.media_play_pause
- id: '1573883685626'
  alias: Notify when printer finishes
  description: ''
  trigger:
  - entity_id: sensor.octoprint_current_state
    from: Printing
    platform: state
    to: Operational
  condition: []
  action:
  - data:
      message: Printer has finished
    service: notify.notify_pushbullet
- id: '1575103717785'
  alias: Notify when washing machine finishes
  description: ''
  trigger:
  - below: 5
    device_id: 8ade2b7fee914993b9c0c0603da67237
    domain: sensor
    entity_id: sensor.0x00158d00026e9fa1_power
    for:
      hours: 0
      minutes: 0
      seconds: 10
    platform: device
    type: value
  condition: []
  action:
  - data:
      message: Washing machine has finished
    service: notify.notify_pushbullet
- id: '1576844234021'
  alias: Kodi volume down
  description: ''
  trigger:
  - entity_id: sensor.0xccccccfffe74d44a_action
    platform: state
    to: rotate_left
  condition: []
  action:
  - data:
      entity_id: media_player.kodi
    service: media_player.volume_down
- id: '1576844393282'
  alias: Kodi volume up
  description: ''
  trigger:
  - entity_id: sensor.0xccccccfffe74d44a_action
    platform: state
    to: rotate_right
  condition: []
  action:
  - data:
      entity_id: media_player.kodi
    service: media_player.volume_up
- id: '1576921942730'
  alias: Kodi Play/Pause
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/ikea_symfonisk_dial
  condition:
  - condition: template
    value_template: '{{ ''play_pause'' in trigger.payload }}'
  action:
  - data:
      entity_id: media_player.kodi
    service: media_player.media_play_pause
- id: d09e759079d6459fa6dd5fae89008ea8
  alias: Kodi set volume
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/ikea_symfonisk_dial
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == ''rotate_stop'' }}'
  action:
  - data_template:
      entity_id: media_player.kodi
      volume_level: '{{ (trigger.payload_json.brightness / 255) | round(2) }}'
    service: media_player.volume_set
