default_config:

http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

tts:
  - platform: google_translate

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

notify:
  - platform: kodi
    name: notify_kodi
    host: kodi.local
    port: 80
  - platform: pushbullet
    name: notify_pushbullet
    api_key: !secret pushbullet_api_key

octoprint:
  host: octopi.local
  api_key: !secret octoprint_api_key
  bed: true
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'

media_player:
  - platform: kodi
    host: kodi.local
    port: 80
    enable_websocket: true
    tcp_port: 9090

camera:
  - platform: bom
    location: Melbourne

weather:
  - platform: bom

sensor:
  - platform: bom
    station: !secret bom_station
    monitored_conditions:
      - apparent_t
      - cloud
      - gust_kmh
      - air_temp
      - rain_trace
      - rel_hum
      - vis_km
      - weather
      - wind_spd_kmh

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homeassistant:
  customize: !include customize.yaml
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Australia/Melbourne
