homeassistant:
  name: Haus
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Australia/Melbourne
  customize: !include customize.yaml

frontend:
config:
updater:
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

notify:
  - platform: kodi
    name: kodi
    host: kodi.local
    port: 80
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet_api_key

camera:
  - platform: mjpeg
    name: OctoPi
    mjpeg_url: http://octopi.local/webcam/?action=stream

switch:
  - platform: tplink
    host: 192.168.1.7
    enable_leds: false

octoprint:
  host: octopi.local
  api_key: !secret octoprint_api_key
  bed: true
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'
  binary_sensors:
    monitored_conditions:

media_player:
  - platform: kodi
    name: kodi
    host: kodi.local
    port: 80

sensor:
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: bom
    station: !secret bom_station
    name: local
    monitored_conditions:
      - apparent_t
      - cloud
      - air_temp
      - rel_hum
  - platform: mqtt
    name: "Washing Temperature"
    state_topic: "sensor/temperature"
    qos: 0
    unit_of_measurement: "ºC"
  - platform: mqtt
    name: "Washing Humidity"
    state_topic: "sensor/humidity"
    qos: 0
    unit_of_measurement: "%"

mqtt:
  broker: localhost
  client_id: haus
  username: haus
  password: !secret mqtt_haus_password

