homeassistant:
  name: Haus
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Australia/Melbourne
  customize: !include customize.yaml

lovelace:
frontend:
config:
updater:

tts:
#  - platform: marytts
#    host: 'localhost'
#    port: 59125
#    codec: 'wav'
#    voice: 'cmu-slt-hsmm'
#    language: 'en-US'
  - platform: picotts
    language: 'en-US'

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

device_tracker:
  - platform: zte
    password: !secret zte_password
    host: 10.0.0.1

notify:
  - platform: kodi
    name: notify_kodi
    host: kodi.local
    port: 80
  - platform: pushbullet
    name: notify_pushbullet
    api_key: !secret pushbullet_api_key

camera:
  - platform: mjpeg
    name: OctoPi
    mjpeg_url: http://octopi.local/webcam/?action=stream

octoprint:
  host: octopi.local
  api_key: !secret octoprint_api_key
  bed: true
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'
  binary_sensors:
    monitored_conditions:

media_player:
  - platform: kodi
    name: kodi
    host: kodi.local
    port: 80

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

sensor:
  - platform: bom
    station: !secret bom_station
    name: local
    monitored_conditions:
      - apparent_t
      - cloud
      - air_temp
      - rel_hum
  - platform: mqtt
    name: "Clothesline Temperature"
    icon: mdi:thermometer
    state_topic: "clothesline/temperature"
    qos: 0
    unit_of_measurement:  "ºC"
  - platform: mqtt
    name: "Clothesline Relative Humidity"
    icon: mdi:water-percent
    state_topic: "clothesline/humidity"
    qos: 0
    unit_of_measurement: "%"
  - platform: mqtt
    name: "Clothesline Heat Index"
    icon: mdi:thermometer
    state_topic: "clothesline/heat_index"
    qos: 0
    unit_of_measurement:  "ºC"
  - platform: mqtt
    name: Zigbee2mqtt Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
mqtt:
  broker: localhost
  client_id: haus
  username: haus
  password: !secret mqtt_haus_password
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Input select for Zigbee2mqtt debug level
input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted

# Input boolean for enabling/disabling joining
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

# Switch for enabling joining
switch:
  - platform: mqtt
    name: "Zigbee2mqtt Main join"
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"

light:
  - name: Sengled Classic 1
    platform: "mqtt"
    state_topic: "zigbee2mqtt/sengled_classic_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    #brightness_state_topic: "zigbee2mqtt/sengled_classic_1"
    #brightness_command_topic: "zigbee2mqtt/sengled_sengled_classic_1/set"
    command_topic: "zigbee2mqtt/sengled_classic_1/set"
  - name: Sengled Classic 2
    platform: "mqtt"
    state_topic: "zigbee2mqtt/sengled_classic_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    #brightness: true
    #brightness_state_topic: "zigbee2mqtt/sengled_classic_1"
    #brightness_command_topic: "zigbee2mqtt/sengled_sengled_classic_1/set"
    command_topic: "zigbee2mqtt/sengled_classic_2/set"

conversation:
  intents:
    start_netflix:
      - Start [up] Netflix
      - Run Netflix
      - Open Netflix
    shuffle_music:
      - Shuffle [my] music
      - Play [some][random] music

intent_script:
  start_netflix:
    speech:
      text: Starting Netflix
    action:
      service: script.start_netflix
  shuffle_music:
    speech:
      text: Shuffling music
    action:
      service: script.shuffle_music
