mobile_app:
updater:
system_health:
config:
logbook:
sun:


http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

snips:

intent_script: !include intent_scripts.yaml

tts:
  - platform: picotts
    language: 'en-GB'

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

notify:
  - platform: kodi
    name: notify_kodi
    host: kodi.local
    port: 80
  - platform: pushbullet
    name: notify_pushbullet
    api_key: !secret pushbullet_api_key

octoprint:
  host: octopi.local
  api_key: !secret octoprint_api_key
  bed: true
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'

media_player:
  - platform: kodi
    host: kodi.local
    port: 80
    enable_websocket: true
    tcp_port: 9090

camera:
  - platform: bom
    location: Melbourne

  - platform: mjpeg
    name: 3D Printer
    still_image_url: http://octopi.local/webcam/?action=snapshot
    mjpeg_url: http://octopi.local/webcam/?action=stream

weather:
  - platform: bom

sensor:
  - platform: rest
    resource: !secret rest_st_george_balance_available
    name: St. George balance
    value_template: '{{ value_json["balanceAvailable"] }}'
    unit_of_measurement: '$'

  - platform: rest
    resource: !secret rest_ing_balance_available
    name: ING balance
    value_template: '{{ value_json["balanceAvailable"] }}'
    unit_of_measurement: '$'

  - platform: rest
    resource: !secret rest_st_george_home_loan
    name: Home loan
    value_template: '{{ value_json["balanceTotal"] }}'
    unit_of_measurement: '$'

  - platform: bom
    station: !secret bom_station
    monitored_conditions:
      - apparent_t
      - cloud
      - gust_kmh
      - air_temp
      - rain_trace
      - rel_hum
      - weather

  - platform: template
    sensors:
      washing_machine:
        friendly_name: "Washing machine"
        value_template: "{{ state_attr('sensor.0x00158d00026e9fa1_power', 'power') | float > 4 }}"

binary_sensor:
  - platform: template
    sensors:
      mailbox:
        friendly_name: "Mailbox"
        entity_id:
          - "binary_sensor.0x00158d000357fe12_contact"
          - "binary_sensor.0x00158d000357feef_contact"
        device_class: motion
        value_template: >-
          {% if is_state('binary_sensor.mailbox', 'off') %}
            {{ is_state('binary_sensor.0x00158d000357fe12_contact', 'on') }}
          {% else %}
            {{ not is_state('binary_sensor.0x00158d000357feef_contact', 'on') }}
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.0x00158d000357fe12_contact', 'on') %}
            mdi:mailbox-up-outline
          {% elif is_state('binary_sensor.0x00158d000357feef_contact', 'on') %}
            mdi:mailbox-outline
          {% else %}
            {{ state_attr('binary_sensor.mailbox.icon') }}
          {% endif %}

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homeassistant:
  customize: !include customize.yaml
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Australia/Melbourne
